### ISSUE TITLE
proposal: Incident Eventlog

### ISSUE THREAD

**Issue by VoyTechnology** [SaferPlace/saferplace#14]
At the moment, when an incident is created, we just keep modifying the original incident. However, I think we can add much more functionality and enable easier addition of functionality by keeping a changelog/actionlog/eventlog of the incident. This would allow us to see more precisely the changes that happened to the incident. The log would only contain logs related to changes of the incident, rather than read operations.

This means that the changed incident structure would change from

```yaml
incidents:
- id: "incident-1"
  timestamp: 111111
  description: "Plastic bottles thrown at pedestrians from a car"
- id: "incident-2"
  timestamp: 222222
  description: "Someone is throwing bottles at people"
  
comments:
 - incident_id: "incident-1"
   author: bob
   comment: ""
   resolution: ACCEPTED
 - incident_id: "incident-2"
   author: voy
   comment: "Multiple Reports, closing"
   resolution: REJECTED
```

Would turn into

```yaml
incidents:
- id: "incident-1"
  timestamp: 111111
  description: "Plastic bottles thrown at pedestrians from a car"
- id: "incident-2"
  timestamp: 222222
  description: "Someone is throwing bottles at people"
  
events:
- incident_id: "incident-1"
  action: resolution_change
  timestamp: 111112
  owner: bob
  content:
    resolution: ACCEPTED
- incident_id: "incident-2"
  action: duplicate
  owner: voy
  timestamp: 222223
  content:
    duplicate_of: "incident-1"
```

What this means:
- We can create more actions, each can be extended by their own handler
- i18n: Since common actions, such as accepting, or rejecting on duplication mean its an action, we can send a translated message to the reporter rather than the comment made by the reviewer
- Easier routing of alerts and subscriptions to only certain events
- Provide only action specific content rather than embed all fields which we might add in the future.
